# Generated by Django 2.1.1 on 2019-01-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=256)),
                ('checked', models.BooleanField(default=False)),
                ('type_notice', models.CharField(choices=[('START_PROJECT', 'Start project'), ('DEADLINE', 'Deadline'), ('BIRTHDAY', 'Birthday'), ('VACATION', 'Vacation'), ('HOLIDAY', 'Holiday')], default='START_PROJECT', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
