# Generated by Django 2.1.1 on 2019-01-16 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190111_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='owner',
        ),
        migrations.AddField(
            model_name='vacation',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
