# Generated by Django 2.1.1 on 2019-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190116_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
