# Generated by Django 2.1.1 on 2019-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190203_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
