# Generated by Django 2.1.1 on 2019-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190203_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.RemoveField(
            model_name='developersonproject',
            name='owner',
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='iban_code',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROCESS', 'In process'), ('SCHEDULED', 'Scheduled'), ('FINISHED', 'Finished')], default='SCHEDULED', max_length=16),
        ),
        migrations.AlterField(
            model_name='developer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='developer',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='all_time_money_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
