# Generated by Django 2.1.1 on 2019-02-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190205_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyBankInfo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='all_time_money_spent',
        ),
        migrations.AlterField(
            model_name='developersonproject',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
