# Generated by Django 2.1.1 on 2018-10-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181003_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='managerinfo',
            name='owner',
        ),
        migrations.AlterField(
            model_name='project',
            name='manager_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Manager'),
        ),
        migrations.DeleteModel(
            name='ManagerInfo',
        ),
    ]
