# Generated by Django 2.1.1 on 2018-10-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181001_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerinfo',
            old_name='owner',
            new_name='user',
        ),
    ]
