# Generated by Django 2.1.1 on 2018-10-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deadlineforgcal_projectstartforgcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActOfPerfJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_act', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_address', models.TextField()),
                ('bank_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('tax_number', models.CharField(max_length=20)),
                ('num_contract_with_dev', models.CharField(max_length=20)),
                ('date_contract_with_dev', models.DateField()),
                ('bank_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.BankInfo')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='developer',
            name='father_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='developer',
            name='tax_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='actofperfjobs',
            name='customer_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AddField(
            model_name='actofperfjobs',
            name='developer_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Developer'),
        ),
        migrations.AddField(
            model_name='developer',
            name='bank_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BankInfo'),
        ),
    ]
