# Generated by Django 2.1.1 on 2018-09-27 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180926_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devsalary',
            name='date',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
