# Generated by Django 2.1.1 on 2018-10-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actofperfjobs_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
    ]
