# Generated by Django 2.1.1 on 2019-01-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190116_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='birthday_date',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
