# Generated by Django 2.1.1 on 2019-01-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190116_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Developer'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager'},
        ),
    ]
