# Generated by Django 2.1.1 on 2018-10-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_developer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actofperfjobs',
            name='customer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AlterField(
            model_name='actofperfjobs',
            name='developer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Developer'),
        ),
    ]
