# Generated by Django 2.1.1 on 2018-10-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181026_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('tax_number', models.CharField(max_length=20)),
                ('num_contract_with_dev', models.CharField(max_length=20)),
                ('date_contract_with_dev', models.DateField()),
                ('sign', models.ImageField(null=True, upload_to='static/signs/')),
                ('bank_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.BankInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_info',
        ),
        migrations.AddField(
            model_name='developer',
            name='sign',
            field=models.ImageField(null=True, upload_to='static/signs/'),
        ),
        migrations.AlterField(
            model_name='actofperfjobs',
            name='customer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
