# Generated by Django 2.1.1 on 2018-10-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181031_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actofperfjobs',
            old_name='customer_info',
            new_name='owner_info',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='customer',
            new_name='owner',
        ),
    ]
