# Generated by Django 2.1.1 on 2018-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_owner_user_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_contract_with_dev',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='father_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='num_contract_with_dev',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tax_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
