# Generated by Django 2.1.1 on 2018-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181107_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_account_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
